stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py 
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  feature_processing:
    cmd: python src/features/feature_processing.py
    params:
    - feature_processing.test_size
    deps:
    - data/raw
    - src/features/feature_processing.py
    outs:
    - data/processed
    - models/pipe.pkl
  model_building:
    cmd: python src/model/model_building.py
    params:
    - model_building.n_estimators
    - model_building.max_depth
    - model_building.min_samples_split
    - model_building.min_samples_leaf
    - model_building.max_features
    - model_building.bootstrap
    deps:
    - data/processed
    - models/pipe.pkl
    - src/model/model_building.py
    outs:
    - models/RandomForest.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed
    - models/RandomForest.pkl
    - src/model/model_evaluation.py
    outs:
    - reports/metrics.json
    - reports/exp_info.json
  register_model:
    cmd: python src/model/register_model.py
    deps:
    - reports/exp_info.json
    - src/model/register_model.py
