stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  feature_processing:
    cmd: python src/features/feature_processing.py
    deps:
    - data/raw
    - src/features/feature_processing.py
    outs:
    - data/processed
    - models/pipe.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - models/pipe.pkl
    - src/model/model_building.py
    outs:
    - models/RandomForest.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed
    - models/RandomForest.pkl
    - src/model/model_evaluation.py
    outs:
    - reports/metrics.json
