name: CI

on: 
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: 'ubuntu-latest'

    steps:

      - name: code checkout
        uses: actions/checkout@v3
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name : install flake8
        run : |
            python -m pip install --upgrade pip
            pip install flake8
      
      - name : run flake8
        run : |
             flake8 src/ --config .flake8
  
  project_testing:
    needs: linting

    runs-on: 'ubuntu-latest'
    
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: run pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run : |
          dvc repro
