name: CI

on: 
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ${{ matrix.OS }}

    strategy:
      matrix:
          OS:  ['ubuntu-latest','windows-latest','macos-latest']
          versions: ['3.9','3.10','3.11']

    steps:

      - name: code checkout
        uses: actions/checkout@v3
      
      - name: set up repository
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.versions }}
      
      - name : install flake8
        run : |
            python -m pip install --upgrade pip
            pip install flake8
      
      - name : run flake8
        run : |
             flake8 src/ --config .flake8
