name: CI

on: 
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: 'ubuntu-latest'

    steps:

      - name: code checkout
        uses: actions/checkout@v3
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name : install flake8
        run : |
            python -m pip install --upgrade pip
            pip install flake8
      
      - name : run flake8
        run : |
             flake8 src/ --config .flake8
  
  project_testing:
    needs: linting

    runs-on: ${{ matrix.OS }}

    strategy:
      matrix:
        OS: ['ubuntu-latest','windows-latest','macos-latest']
        versions: ['3.9','3.10','3.11']
    
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.versions }}
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: configure aws credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-southeast-2
      
      - name: Pull data from s3
        run : dvc pull
      
      - name: run pipeline
        run : |
          dvc repro
